// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package db

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func NewDbConnection() DataSource {
	mongoDriver := NewMongoDB()
	sqLxDriver := NewMariaDB()
	dbDataSource := NewDataSource(mongoDriver, sqLxDriver)
	return dbDataSource
}
