// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package api

import (
	"github.com/prongbang/gomulti-source/pkg/api/post"
	"github.com/prongbang/gomulti-source/pkg/db"
)

// Injectors from wire.go:

func CreateAPI(dbSource db.DataSource) API {
	route := post.NewPostAPI(dbSource)
	apiAPI := NewAPI(route)
	return apiAPI
}
