// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package post

import (
	"github.com/prongbang/gomulti-source/pkg/db"
)

// Injectors from wire.go:

func NewPostAPI(dbSource db.DataSource) Route {
	postDataSource := NewDataSource(dbSource)
	postRepository := NewRepository(postDataSource)
	postUseCase := NewUseCase(postRepository)
	postHandler := NewHandler(postUseCase)
	postRoute := NewRoute(postHandler)
	return postRoute
}
